# Generated by Django 3.0.4 on 2020-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('fechaIngresoProducto', models.CharField(max_length=100)),
                ('fechaCaducidadProducto', models.CharField(max_length=100)),
                ('cantidadProducto', models.IntegerField()),
                ('ventasProductoPieza', models.IntegerField()),
            ],
        ),
    ]
